### ISSUE TITLE
Handbook needs a find in page option.

### ISSUE THREAD

**Issue by timparenti** [cmukgb/ctfws-timer-android#12]
Need from the field, S19.

**Comment by nwf** [comment]
The mechanics are exposed as https://developer.android.com/reference/android/webkit/WebView.html#findAllAsync(java.lang.String) and https://developer.android.com/reference/android/webkit/WebView.html#findNext(boolean), but I don't know what kind of UI is appropriate.

**Comment by nwf** [comment]
https://developer.android.com/reference/android/view/ActionMode.html#setCustomView(android.view.View) gives the hint that custom views in ActionMode overlays are useful for search boxes, and I think that is indeed what we want for the UI.
