### ISSUE TITLE
Main icons aren't really optimal.

### ISSUE THREAD

**Issue by timparenti** [cmukgb/ctfws-timer-android#13]
They make no sense. 

* Right turn caution sign for rules? Not a book?
* Download icon for reconnect? Not some sort of refresh symbol?

**Comment by nwf** [comment]
Did my best to pull from the limited set Android offered by default.  Replacements more than welcome.
The right turn sign was intended to read as "directions" and for the life of me there doesn't seem to be a refresh symbol in the default iconography.

**Comment by timparenti** [comment]
Refresh button should probably also be closer to the "server URI/state" information.

@nwf If you want me to look into options for icons, let me know what format(s) you need them in.

**Comment by nwf** [comment]
The refresh icon can probably just go away.  As it stands, tapping the table at the bottom causes a reconnect and the app's even nice enough to say so when it's disconnected and waiting for the autoreconnect timer to trigger.

**Comment by timparenti** [comment]
I guess, in that case, it might make sense for the "refresh" icon to only appear down there as part of the disconnect message, to allow the user to re-try sooner than the auto-reconnect might otherwise.
