### ISSUE TITLE
Expose basic debug info under "About"

### ISSUE THREAD

**Issue by timparenti** [cmukgb/ctfws-timer-android#15]
Not that it would've helped much with #9, but even anything that displays the app version and (ideally) Android version, along with any other critical information that would assist in being able to dig any deeper in testing.

Only bother with data that can automatically be pulled.  If you have to update the app version manually in more than the required place, it's probably not worth it.

**Comment by nwf** [comment]
For future-me: the strings are statically exposed in `BuildConfig` (see https://developer.android.com/studio/build/gradle-tips) and https://stackoverflow.com/questions/28498688/gradle-script-to-autoversion-and-include-the-commit-hash-in-android offers a way of embedding the `git` hash into the build product, also in a static way.

I'll just add another tab to the `About` activity, I think.
