### ISSUE TITLE
Rename default branch

### ISSUE THREAD

**Issue by nwf** [cmukgb/ctfws-timer-android#23]
@timparenti, I appear to lack sufficient rights to the repo.  I've made `main` a clone of `master` already; they just need to be swizzled in the UI.

**Comment by timparenti** [comment]
> I've made `main` a clone of `master` already

Ah, don't do that! It throws an extra step in the process, as the default branch can't be renamed to something that already exists.

I've just deleted the errant branch and renamed the default accordingly.
